/*import React, { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from 'react-query';
import axios from 'axios';
import { FileText, Download, Edit, Eye, ArrowLeft, CheckCircle, Clock } from 'lucide-react';
import LoadingSpinner from '../components/UI/LoadingSpinner';
import { toast } from 'react-toastify';

const ReportDetailsPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const { data, isLoading, error, refetch } = useQuery(
    ['report', id],
    async () => {
      const response = await axios.get(`/api/reports/${id}`);
      return response.data;
    },
    {
      refetchInterval: (data) => {
        // Keep polling if report is still processing
        if (data?.report?.status === 'processing') {
          return 3000; // Poll every 3 seconds
        }
        return false; // Stop polling once completed
      }
    }
  );

  const report = data?.report;

  const handleDownload = async () => {
    try {
      window.open(`/api/reports/${id}/download`, '_blank');
      toast.success('Report downloading...');
    } catch (err) {
      console.error('Error downloading report:', err);
      toast.error('Failed to download report');
    }
  };

  const getStatusDisplay = () => {
    const statusConfig = {
      draft: { icon: FileText, color: 'text-gray-400', label: 'Draft' },
      processing: { icon: Clock, color: 'text-orange-400', label: 'Processing...' },
      completed: { icon: CheckCircle, color: 'text-blue-400', label: 'Completed' },
      finalized: { icon: CheckCircle, color: 'text-green-400', label: 'Finalized' }
    };

    const config = statusConfig[report?.status] || statusConfig.draft;
    const Icon = config.icon;

    return (
      <div className="flex items-center space-x-2">
        <Icon className={`h-5 w-5 ${config.color}`} />
        <span className="text-dark-100 font-medium">{config.label}</span>
      </div>
    );
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <LoadingSpinner size="large" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <p className="text-red-400">Error loading report: {error.message}</p>
        <button onClick={() => refetch()} className="btn-primary mt-4">
          Retry
        </button>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center py-12">
        <p className="text-dark-400">Report not found</p>
        <button onClick={() => navigate('/reports')} className="btn-primary mt-4">
          Back to Reports
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header *//*same here*/
/*<div className="flex items-center justify-between">
  <div className="flex items-center space-x-4">
    <button
      onClick={() => navigate('/reports')}
      className="text-primary-400 hover:text-primary-300 flex items-center"
    >
      <ArrowLeft className="h-5 w-5 mr-2" />
      Back
    </button>
    <div>
      <h1 className="text-3xl font-bold text-dark-100">{report.title}</h1>
      <p className="text-dark-300 mt-1">
        Case: {report.caseId?.caseId || 'N/A'} - {report.caseId?.title || 'N/A'}
      </p>
    </div>
  </div>
  {report.status === 'completed' || report.status === 'finalized' ? (
    <button
      onClick={handleDownload}
      className="btn-primary flex items-center"
    >
      <Download className="h-4 w-4 mr-2" />
      Download
    </button>
  ) : null}
</div>

{/* Status Card *//*put this } symbol if you get error
/* <div className="card">
  <div className="card-body">
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
      <div>
        <p className="text-dark-400 text-sm mb-1">Status</p>
        {getStatusDisplay()}
      </div>
      <div>
        <p className="text-dark-400 text-sm mb-1">Generated By</p>
        <p className="text-dark-100 font-medium">
          {report.generatedBy?.firstName} {report.generatedBy?.lastName}
        </p>
      </div>
      <div>
        <p className="text-dark-400 text-sm mb-1">Created</p>
        <p className="text-dark-100 font-medium">
          {new Date(report.createdAt).toLocaleDateString()}
        </p>
      </div>
      <div>
        <p className="text-dark-400 text-sm mb-1">Report Type</p>
        <p className="text-dark-100 font-medium">
          {report.aiGenerated ? 'AI Generated' : 'Manual'}
        </p>
      </div>
    </div>
  </div>
</div>*/

/*{/* Content Section */
/*{report.status === 'processing' ? (
  <div className="card">
    <div className="card-body text-center py-12">
      <Clock className="h-12 w-12 text-orange-400 mx-auto mb-4 animate-spin" />
      <h3 className="text-lg font-medium text-dark-100 mb-2">Report is being generated</h3>
      <p className="text-dark-400 mb-4">
        Your AI-powered forensic report is being generated. This may take a few moments.
      </p>
      <button
        onClick={() => refetch()}
        className="btn-secondary inline-flex items-center"
      >
        <Clock className="h-4 w-4 mr-2" />
        Check Status
      </button>
    </div>
  </div>
) : report.status === 'completed' || report.status === 'finalized' ? (
  <div className="card">
    <div className="card-header">
      <h2 className="text-xl font-semibold text-dark-100">Report Content</h2>
    </div>
    <div className="card-body">
      <div className="prose prose-invert max-w-none">
        {report.content ? (
          <div className="space-y-4 text-dark-300">
            {typeof report.content === 'string' ? (
              <p className="whitespace-pre-wrap">{report.content}</p>
            ) : Array.isArray(report.content) ? (
              report.content.map((section, idx) => (
                <div key={idx}>
                  {section.heading && (
                    <h3 className="text-lg font-semibold text-dark-100 mt-4 mb-2">
                      {section.heading}
                    </h3>
                  )}
                  {section.text && (
                    <p className="whitespace-pre-wrap">{section.text}</p>
                  )}
                </div>
              ))
            ) : (
              <pre className="bg-dark-800 p-4 rounded overflow-auto">
                {JSON.stringify(report.content, null, 2)}
              </pre>
            )}
          </div>
        ) : (
          <p className="text-dark-400">No content available</p>
        )}
      </div>
    </div>
  </div>
) : (
  <div className="card">
    <div className="card-body text-center py-12">
      <FileText className="h-12 w-12 text-dark-500 mx-auto mb-4" />
      <h3 className="text-lg font-medium text-dark-100 mb-2">Report is in draft status</h3>
      <p className="text-dark-400">
        This report hasn't been generated yet or is waiting to be finalized.
      </p>
    </div>
  </div>
)}*/

/*{/* Metadata Section *//*same here
{report.metadata && (
  <div className="card">
    <div className="card-header">
      <h2 className="text-xl font-semibold text-dark-100">Metadata</h2>
    </div>
    <div className="card-body">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {report.metadata.processingTime && (
          <div>
            <p className="text-dark-400 text-sm mb-1">Processing Time</p>
            <p className="text-dark-100 font-medium">
              {(report.metadata.processingTime / 1000).toFixed(2)}s
            </p>
          </div>
        )}
        {report.metadata.wordCount && (
          <div>
            <p className="text-dark-400 text-sm mb-1">Word Count</p>
            <p className="text-dark-100 font-medium">{report.metadata.wordCount}</p>
          </div>
        )}
        {report.metadata.error && (
          <div className="col-span-full">
            <p className="text-dark-400 text-sm mb-1">Error</p>
            <p className="text-red-400 font-medium">{report.metadata.error}</p>
          </div>
        )}
      </div>
    </div>
  </div>
)}
</div>
);
};

export default ReportDetailsPage;*/
/*import React from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useQuery } from "react-query";
import axios from "axios";
import {
  FileText,
  Download,
  ArrowLeft,
  CheckCircle,
  Clock
} from "lucide-react";

import LoadingSpinner from "../components/UI/LoadingSpinner";
import { toast } from "react-toastify";

const ReportDetailsPage = () => {

  const { id } = useParams();
  const navigate = useNavigate();


  const { data, isLoading, error, refetch } = useQuery(
    ["report", id],
    async () => {

      const token = localStorage.getItem("token");

      const response = await axios.get(`/api/reports/${id}`, {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });

      return response.data;
    },
    {
      refetchInterval: (data) => {
        if (data?.report?.status === "processing") {
          return 3000;
        }
        return false;
      }
    }
  );

  const report = data?.report;


  const handleDownload = async () => {

    try {

      const token = localStorage.getItem("token");

      const response = await axios.get(
        `/api/reports/${id}/download`,
        {
          responseType: "blob",
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      );

      const url = window.URL.createObjectURL(new Blob([response.data]));

      const link = document.createElement("a");

      link.href = url;
      link.setAttribute("download", `${report.reportId}.pdf`);

      document.body.appendChild(link);
      link.click();
      link.remove();

      toast.success("Report downloaded successfully");

    } catch (err) {

      console.error(err);
      toast.error("Failed to download report");

    }

  };


  const getStatusDisplay = () => {

    const statusConfig = {
      draft: { icon: FileText, color: "text-gray-400", label: "Draft" },
      processing: { icon: Clock, color: "text-orange-400", label: "Processing..." },
      completed: { icon: CheckCircle, color: "text-blue-400", label: "Completed" },
      finalized: { icon: CheckCircle, color: "text-green-400", label: "Finalized" }
    };

    const config = statusConfig[report?.status] || statusConfig.draft;

    const Icon = config.icon;

    return (
      <div className="flex items-center space-x-2">
        <Icon className={`h-5 w-5 ${config.color}`} />
        <span className="text-dark-100 font-medium">{config.label}</span>
      </div>
    );
  };


  if (isLoading) {

    return (
      <div className="flex items-center justify-center h-64">
        <LoadingSpinner size="large" />
      </div>
    );

  }


  if (error) {

    return (
      <div className="text-center py-12">
        <p className="text-red-400">
          Error loading report: {error.message}
        </p>

        <button
          onClick={() => refetch()}
          className="btn-primary mt-4"
        >
          Retry
        </button>
      </div>
    );

  }


  if (!report) {

    return (
      <div className="text-center py-12">
        <p className="text-dark-400">Report not found</p>

        <button
          onClick={() => navigate("/reports")}
          className="btn-primary mt-4"
        >
          Back to Reports
        </button>
      </div>
    );

  }



  return (

    <div className="space-y-6">

      {/* HEADER */

/*<div className="flex items-center justify-between">

  <div className="flex items-center space-x-4">

    <button
      onClick={() => navigate("/reports")}
      className="text-primary-400 hover:text-primary-300 flex items-center"
    >
      <ArrowLeft className="h-5 w-5 mr-2" />
      Back
    </button>

    <div>
      <h1 className="text-3xl font-bold text-dark-100">
        {report.title}
      </h1>

      <p className="text-dark-300 mt-1">
        Case: {report.caseId?.caseId || "N/A"} - {report.caseId?.title || "N/A"}
      </p>
    </div>

  </div>


  {(report.status === "completed" || report.status === "finalized") && (

    <button
      onClick={handleDownload}
      className="btn-primary flex items-center"
    >
      <Download className="h-4 w-4 mr-2" />
      Download
    </button>

  )}

</div>



{/* STATUS CARD */

/*<div className="card">

  <div className="card-body">

    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">

      <div>
        <p className="text-dark-400 text-sm mb-1">Status</p>
        {getStatusDisplay()}
      </div>

      <div>
        <p className="text-dark-400 text-sm mb-1">Generated By</p>
        <p className="text-dark-100 font-medium">
          {report.generatedBy?.firstName} {report.generatedBy?.lastName}
        </p>
      </div>

      <div>
        <p className="text-dark-400 text-sm mb-1">Created</p>
        <p className="text-dark-100 font-medium">
          {new Date(report.createdAt).toLocaleDateString()}
        </p>
      </div>

      <div>
        <p className="text-dark-400 text-sm mb-1">Report Type</p>
        <p className="text-dark-100 font-medium">
          {report.aiGenerated ? "AI Generated" : "Manual"}
        </p>
      </div>

    </div>

  </div>

</div>



{/* REPORT CONTENT */

/*<div className="card">

  <div className="card-header">
    <h2 className="text-xl font-semibold text-dark-100">
      Report Content
    </h2>
  </div>

  <div className="card-body">

    <div className="space-y-8 text-dark-300 leading-relaxed">

      <div>
        <h2 className="text-xl font-bold text-dark-100 mb-2">
          Executive Summary
        </h2>
        <p className="whitespace-pre-line">
          {report.content?.executiveSummary}
        </p>
      </div>


      <div>
        <h2 className="text-xl font-bold text-dark-100 mb-2">
          Incident Overview
        </h2>
        <p className="whitespace-pre-line">
          {report.content?.incidentOverview}
        </p>
      </div>


      <div>
        <h2 className="text-xl font-bold text-dark-100 mb-2">
          Evidence Summary
        </h2>
        <p className="whitespace-pre-line">
          {report.content?.evidenceSummary}
        </p>
      </div>


      <div>
        <h2 className="text-xl font-bold text-dark-100 mb-2">
          Technical Findings
        </h2>
        <p className="whitespace-pre-line">
          {report.content?.technicalFindings}
        </p>
      </div>


      <div>
        <h2 className="text-xl font-bold text-dark-100 mb-2">
          Timeline of Events
        </h2>
        <p className="whitespace-pre-line">
          {report.content?.timeline}
        </p>
      </div>


      <div>
        <h2 className="text-xl font-bold text-dark-100 mb-2">
          Conclusion
        </h2>
        <p className="whitespace-pre-line">
          {report.content?.conclusion}
        </p>
      </div>


    </div>

  </div>

</div>

</div>

);

};

export default ReportDetailsPage;*/
import React from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useQuery } from "react-query";
import axios from "axios";
import {
  FileText,
  Download,
  ArrowLeft,
  CheckCircle,
  Clock
} from "lucide-react";

import LoadingSpinner from "../components/UI/LoadingSpinner";
import { toast } from "react-toastify";

const ReportDetailsPage = () => {

  const { id } = useParams();
  const navigate = useNavigate();

  const { data, isLoading, error, refetch } = useQuery(
    ["report", id],
    async () => {

      const token = localStorage.getItem("token");

      const response = await axios.get(`/api/reports/${id}`, {
        headers: { Authorization: `Bearer ${token}` }
      });

      return response.data;

    },
    {
      refetchInterval: (data) => {
        if (data?.report?.status === "processing") return 3000;
        return false;
      }
    }
  );

  const report = data?.report;

  const handleDownload = async () => {

    try {

      const token = localStorage.getItem("token");

      const response = await axios.get(
        `/api/reports/${id}/download`,
        {
          responseType: "blob",
          headers: { Authorization: `Bearer ${token}` }
        }
      );

      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement("a");

      link.href = url;
      link.setAttribute("download", `${report.reportId}.pdf`);

      document.body.appendChild(link);
      link.click();
      link.remove();

      toast.success("Report downloaded");

    } catch (err) {

      console.error(err);
      toast.error("Download failed");

    }

  };

  const getStatusDisplay = () => {

    const statusConfig = {

      draft: { icon: FileText, color: "text-gray-400", label: "Draft" },
      processing: { icon: Clock, color: "text-orange-400", label: "Processing" },
      completed: { icon: CheckCircle, color: "text-blue-400", label: "Completed" },
      finalized: { icon: CheckCircle, color: "text-green-400", label: "Finalized" }

    };

    const config = statusConfig[report?.status] || statusConfig.draft;
    const Icon = config.icon;

    return (
      <div className="flex items-center space-x-2">
        <Icon className={`h-5 w-5 ${config.color}`} />
        <span className="text-dark-100 font-medium">{config.label}</span>
      </div>
    );

  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <LoadingSpinner size="large" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <p className="text-red-400">Error loading report</p>
        <button onClick={() => refetch()} className="btn-primary mt-4">
          Retry
        </button>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center py-12">
        <p className="text-dark-400">Report not found</p>
        <button onClick={() => navigate("/reports")} className="btn-primary mt-4">
          Back
        </button>
      </div>
    );
  }

  const evidenceRows = [
    ["Suspicious File", "system_update_patch.scr"],
    ["Browser History", "Access to suspicious portal"],
    ["Network Logs", "Connection to external IP"],
    ["Registry Entry", "Persistence mechanism detected"],
    ["Email Artifact", "Email containing suspicious attachment"]
  ];

  const timelineRows = report.content?.timeline
    ? report.content.timeline.split("\n").map(row => {
      const parts = row.trim().split(" ");
      return [parts.shift(), parts.join(" ")];
    })
    : [];

  return (

    <div className="space-y-6">

      <div className="flex items-center justify-between">

        <div className="flex items-center space-x-4">

          <button
            onClick={() => navigate("/reports")}
            className="text-primary-400 hover:text-primary-300 flex items-center"
          >
            <ArrowLeft className="h-5 w-5 mr-2" />
            Back
          </button>

          <div>
            <h1 className="text-3xl font-bold text-dark-100">{report.title}</h1>
            <p className="text-dark-300 mt-1">
              Case: {report.caseId?.caseId || "N/A"}
            </p>
          </div>

        </div>

        {(report.status === "completed" || report.status === "finalized") && (

          <button
            onClick={handleDownload}
            className="btn-primary flex items-center"
          >
            <Download className="h-4 w-4 mr-2" />
            Download
          </button>

        )}

      </div>

      <div className="card">

        <div className="card-header">
          <h2 className="text-xl font-semibold text-dark-100">Report Content</h2>
        </div>

        <div className="card-body space-y-10 text-dark-300">

          <div>
            <h2 className="text-xl font-bold text-dark-100 mb-3 border-b border-gray-600 pb-1">
              Executive Summary
            </h2>
            <p className="whitespace-pre-line">{report.content?.executiveSummary}</p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-dark-100 mb-3 border-b border-gray-600 pb-1">
              Incident Overview
            </h2>
            <p className="whitespace-pre-line">{report.content?.incidentOverview}</p>
          </div>

          <div>

            <h2 className="text-xl font-bold text-dark-100 mb-3 border-b border-gray-600 pb-1">
              Evidence Summary
            </h2>

            <table className="w-full border border-gray-600">

              <thead className="bg-gray-800 text-dark-100">
                <tr>
                  <th className="border border-gray-600 p-2">Evidence Type</th>
                  <th className="border border-gray-600 p-2">Description</th>
                </tr>
              </thead>

              <tbody>

                {evidenceRows.map((row, i) => (
                  <tr key={i}>
                    <td className="border border-gray-600 p-2">{row[0]}</td>
                    <td className="border border-gray-600 p-2">{row[1]}</td>
                  </tr>
                ))}

              </tbody>

            </table>

          </div>

          <div>
            <h2 className="text-xl font-bold text-dark-100 mb-3 border-b border-gray-600 pb-1">
              Technical Findings
            </h2>
            <p className="whitespace-pre-line">{report.content?.technicalFindings}</p>
          </div>

          <div>

            <h2 className="text-xl font-bold text-dark-100 mb-3 border-b border-gray-600 pb-1">
              Timeline of Events
            </h2>

            <table className="w-full border border-gray-600">

              <thead className="bg-gray-800 text-dark-100">
                <tr>
                  <th className="border border-gray-600 p-2">Time</th>
                  <th className="border border-gray-600 p-2">Event</th>
                </tr>
              </thead>

              <tbody>

                {timelineRows.map((row, i) => (
                  <tr key={i}>
                    <td className="border border-gray-600 p-2">{row[0]}</td>
                    <td className="border border-gray-600 p-2">{row[1]}</td>
                  </tr>
                ))}

              </tbody>

            </table>

          </div>

          <div>
            <h2 className="text-xl font-bold text-dark-100 mb-3 border-b border-gray-600 pb-1">
              Conclusion
            </h2>
            <p className="whitespace-pre-line">{report.content?.conclusion}</p>
          </div>

        </div>

      </div>

    </div>

  );

};

export default ReportDetailsPage;