/*const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');

// PDF Export Service
const generatePDF = async (report) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];
      
      // Collect PDF data
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
      
      // Header
      doc.fontSize(20).text('DIGITAL FORENSIC REPORT', { align: 'center' });
      doc.moveDown();
      
      // Watermark for draft reports
      if (report.status !== 'finalized') {
        doc.fontSize(60)
           .fillColor('red', 0.3)
           .text('DRAFT', 200, 300, { align: 'center', rotate: 45 });
        doc.fillColor('black');
      }
      
      // Report metadata
      doc.fontSize(12);
      doc.text(`Report ID: ${report.reportId}`, { continued: true });
      doc.text(`Version: ${report.version}`, { align: 'right' });
      doc.text(`Case ID: ${report.caseId.caseId}`);
      doc.text(`Generated: ${report.createdAt.toDateString()}`);
      doc.text(`Generated by: ${report.generatedBy.firstName} ${report.generatedBy.lastName}`);
      
      if (report.finalizedBy) {
        doc.text(`Finalized by: ${report.finalizedBy.firstName} ${report.finalizedBy.lastName}`);
        doc.text(`Finalized: ${report.finalizedAt.toDateString()}`);
      }
      
      doc.moveDown(2);
      
      // Report title
      doc.fontSize(16).text(report.title, { underline: true });
      doc.moveDown();
      
      // Report sections
      const sections = [
        { title: 'Executive Summary', content: report.content.executiveSummary },
        { title: 'Incident Overview', content: report.content.incidentOverview },
        { title: 'Evidence Summary', content: report.content.evidenceSummary },
        { title: 'Technical Findings', content: report.content.technicalFindings },
        { title: 'Timeline of Events', content: report.content.timeline },
        { title: 'Conclusion', content: report.content.conclusion },
        { title: 'Recommendations', content: report.content.recommendations }
      ];
      
      sections.forEach(section => {
        if (section.content) {
          doc.fontSize(14).text(section.title, { underline: true });
          doc.moveDown(0.5);
          doc.fontSize(11).text(section.content || 'No content provided.');
          doc.moveDown(1.5);
        }
      });
      
      // Chain of custody section
      doc.addPage();
      doc.fontSize(16).text('Chain of Custody', { underline: true });
      doc.moveDown();
      
      doc.fontSize(11);
      doc.text(`Report Created: ${report.createdAt.toISOString()}`);
      doc.text(`Created by: ${report.generatedBy.firstName} ${report.generatedBy.lastName}`);
      
      if (report.revisionHistory && report.revisionHistory.length > 0) {
        doc.moveDown();
        doc.text('Revision History:', { underline: true });
        report.revisionHistory.forEach(revision => {
          doc.text(`Version ${revision.version}: ${revision.editedAt.toDateString()} by ${revision.editedBy.firstName} ${revision.editedBy.lastName}`);
          if (revision.changes) {
            doc.text(`  Changes: ${revision.changes}`);
          }
        });
      }
      
      // Digital signature placeholder
      doc.moveDown(2);
      doc.text('Digital Signature:', { underline: true });
      doc.moveDown();
      doc.text('Signature: _________________________');
      doc.text('Date: _________________________');
      doc.text('Title: _________________________');
      
      // Footer
      doc.fontSize(8);
      doc.text(`Generated on ${new Date().toISOString()}`, 50, doc.page.height - 50);
      doc.text(`Page 1 of 1`, doc.page.width - 100, doc.page.height - 50);
      
      doc.end();
      
    } catch (error) {
      reject(error);
    }
  });
};

// DOCX Export Service
const generateDOCX = async (report) => {
  try {
    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: 'DIGITAL FORENSIC REPORT',
                bold: true,
                size: 32
              })
            ],
            heading: HeadingLevel.TITLE,
            alignment: 'center'
          }),
          
          // Metadata
          new Paragraph({
            children: [
              new TextRun({ text: `Report ID: ${report.reportId}\n`, bold: true }),
              new TextRun({ text: `Version: ${report.version}\n` }),
              new TextRun({ text: `Case ID: ${report.caseId.caseId}\n` }),
              new TextRun({ text: `Generated: ${report.createdAt.toDateString()}\n` }),
              new TextRun({ text: `Generated by: ${report.generatedBy.firstName} ${report.generatedBy.lastName}\n` })
            ]
          }),
          
          // Draft watermark
          ...(report.status !== 'finalized' ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'DRAFT',
                  bold: true,
                  color: 'FF0000',
                  size: 48
                })
              ],
              alignment: 'center'
            })
          ] : []),
          
          // Report title
          new Paragraph({
            children: [
              new TextRun({
                text: report.title,
                bold: true,
                size: 24
              })
            ],
            heading: HeadingLevel.HEADING_1
          }),
          
          // Executive Summary
          ...(report.content.executiveSummary ?[
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Executive Summary',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.executiveSummary
                })
              ]
            })
          ] : []),
          
          // Incident Overview
          ...(report.content.incidentOverview ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Incident Overview',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.incidentOverview
                })
              ]
            })
          ] : []),
          
          // Evidence Summary
          ...(report.content.evidenceSummary ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Evidence Summary',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.evidenceSummary
                })
              ]
            })
          ] : []),
          
          // Technical Findings
          ...(report.content.technicalFindings ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Technical Findings',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.technicalFindings
                })
              ]
            })
          ] : []),
          
          // Timeline
          ...(report.content.timeline ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Timeline of Events',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.timeline
                })
              ]
            })
          ] : []),
          
          // Conclusion
          ...(report.content.conclusion ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Conclusion',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.conclusion
                })
              ]
            })
          ] : []),
          
          // Recommendations
          ...(report.content.recommendations ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Recommendations',
                  bold: true,
                  size: 20
                })
              ],
              heading: HeadingLevel.HEADING_2
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: report.content.recommendations
                })
              ]
            })
          ] : []),
          
          // Chain of Custody
          new Paragraph({
            children: [
              new TextRun({
                text: 'Chain of Custody',
                bold: true,
                size: 20
              })
            ],
            heading: HeadingLevel.HEADING_2
          }),
          
          new Paragraph({
            children: [
              new TextRun({
                text: `Report Created: ${report.createdAt.toISOString()}\n`
              }),
              new TextRun({
                text: `Created by: ${report.generatedBy.firstName} ${report.generatedBy.lastName}\n`
              })
            ]
          }),
          
          // Revision History
          ...(report.revisionHistory && report.revisionHistory.length > 0 ? [
            new Paragraph({
              children: [
                new TextRun({
                  text: 'Revision History',
                  bold: true
                })
              ]
            }),
            ...report.revisionHistory.map(revision => 
              new Paragraph({
                children: [
                  new TextRun({
                    text: `Version ${revision.version}: ${revision.editedAt.toDateString()} by ${revision.editedBy.firstName} ${revision.editedBy.lastName}`
                  }),
                  ...(revision.changes ? [
                    new TextRun({
                      text: `\n  Changes: ${revision.changes}`
                    })
                  ] : [])
                ]
              })
            )
          ] : []),
          
          // Digital Signature
          new Paragraph({
            children: [
              new TextRun({
                text: 'Digital Signature',
                bold: true,
                size: 16
              })
            ]
          }),
          
          new Paragraph({
            children: [
              new TextRun({ text: 'Signature: _________________________\n' }),
              new TextRun({ text: 'Date: _________________________\n' }),
              new TextRun({ text: 'Title: _________________________\n' })
            ]
          })
        ]
      }]
    });
    
    return await Packer.toBuffer(doc);
    
  } catch (error) {
    console.error('DOCX generation error:', error);
    throw error;
  }
};

module.exports = {
  generatePDF,
  generateDOCX
};*/
/*const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, Table, TableRow, TableCell, WidthType } = require("docx");



function parseContent(report) {

  if (typeof report.content === "string") {

    try {
      return JSON.parse(report.content);
    } catch {
      return {};
    }

  }

  return report.content || {};

}



const generatePDF = async (report) => {

  return new Promise((resolve) => {

    const doc = new PDFDocument({ margin: 50 });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));

    doc.on("end", () => {

      resolve(Buffer.concat(buffers));

    });

    const c = parseContent(report);

    doc.fontSize(20).text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });

    doc.moveDown();

    doc.fontSize(14).text("Executive Summary", { underline: true });
    doc.fontSize(11).text(c.executiveSummary);
    doc.moveDown();

    doc.fontSize(14).text("Incident Overview", { underline: true });
    doc.fontSize(11).text(c.incidentOverview);
    doc.moveDown();

    doc.fontSize(14).text("Evidence Summary", { underline: true });
    doc.moveDown();

    doc.fontSize(11).text(c.evidenceSummary);
    doc.moveDown();

    doc.fontSize(14).text("Technical Findings", { underline: true });
    doc.fontSize(11).text(c.technicalFindings);
    doc.moveDown();

    doc.fontSize(14).text("Timeline of Events", { underline: true });
    doc.fontSize(11).text(c.timeline);
    doc.moveDown();

    doc.fontSize(14).text("Conclusion", { underline: true });
    doc.fontSize(11).text(c.conclusion);

    doc.end();

  });

};



const generateDOCX = async (report) => {

  const c = parseContent(report);

  const doc = new Document({

    sections: [{

      children: [

        new Paragraph({ text: "DIGITAL FORENSIC INVESTIGATION REPORT", heading: "Heading1" }),

        new Paragraph(""),

        new Paragraph({ text: "Executive Summary", heading: "Heading2" }),

        new Paragraph(c.executiveSummary),

        new Paragraph(""),

        new Paragraph({ text: "Incident Overview", heading: "Heading2" }),

        new Paragraph(c.incidentOverview),

        new Paragraph(""),

        new Paragraph({ text: "Evidence Summary", heading: "Heading2" }),

        new Paragraph(c.evidenceSummary),

        new Paragraph(""),

        new Paragraph({ text: "Technical Findings", heading: "Heading2" }),

        new Paragraph(c.technicalFindings),

        new Paragraph(""),

        new Paragraph({ text: "Timeline of Events", heading: "Heading2" }),

        new Paragraph(c.timeline),

        new Paragraph(""),

        new Paragraph({ text: "Conclusion", heading: "Heading2" }),

        new Paragraph(c.conclusion)

      ]

    }]

  });

  return await Packer.toBuffer(doc);

};



module.exports = {

  generatePDF,
  generateDOCX

};*/
/*const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph } = require("docx");

function parseContent(report) {

  if (typeof report.content === "string") {

    try {
      return JSON.parse(report.content);
    } catch {
      return {};
    }

  }

  return report.content || {};

}

const generatePDF = async (report) => {

  return new Promise((resolve) => {

    const doc = new PDFDocument({ margin: 50 });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const c = parseContent(report);

    doc.fontSize(20).text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });

    doc.moveDown();

    doc.fontSize(14).text("Executive Summary", { underline: true });
    doc.fontSize(11).text(c.executiveSummary);
    doc.moveDown();

    doc.fontSize(14).text("Incident Overview", { underline: true });
    doc.fontSize(11).text(c.incidentOverview);
    doc.moveDown();

    doc.fontSize(14).text("Evidence Summary", { underline: true });
    doc.text("Suspicious File : system_update_patch.scr");
    doc.text("Browser History : Access to suspicious portal");
    doc.text("Network Logs : Connection to external IP");
    doc.text("Registry Entry : Persistence mechanism detected");
    doc.text("Email Artifact : Email containing suspicious attachment");

    doc.moveDown();

    doc.fontSize(14).text("Technical Findings", { underline: true });
    doc.fontSize(11).text(c.technicalFindings);

    doc.moveDown();

    doc.fontSize(14).text("Timeline of Events", { underline: true });

    if (c.timeline) {
      c.timeline.split("\n").forEach(line => {
        doc.text(line);
      });
    }

    doc.moveDown();

    doc.fontSize(14).text("Conclusion", { underline: true });
    doc.fontSize(11).text(c.conclusion);

    doc.end();

  });

};

const generateDOCX = async (report) => {

  const c = parseContent(report);

  const doc = new Document({

    sections: [{

      children: [

        new Paragraph({ text: "DIGITAL FORENSIC INVESTIGATION REPORT", heading: "Heading1" }),

        new Paragraph(""),

        new Paragraph({ text: "Executive Summary", heading: "Heading2" }),
        new Paragraph(c.executiveSummary),

        new Paragraph(""),

        new Paragraph({ text: "Incident Overview", heading: "Heading2" }),
        new Paragraph(c.incidentOverview),

        new Paragraph(""),

        new Paragraph({ text: "Evidence Summary", heading: "Heading2" }),
        new Paragraph("Suspicious File : system_update_patch.scr"),
        new Paragraph("Browser History : Access to suspicious portal"),
        new Paragraph("Network Logs : Connection to external IP"),

        new Paragraph(""),

        new Paragraph({ text: "Technical Findings", heading: "Heading2" }),
        new Paragraph(c.technicalFindings),

        new Paragraph(""),

        new Paragraph({ text: "Timeline of Events", heading: "Heading2" }),
        new Paragraph(c.timeline),

        new Paragraph(""),

        new Paragraph({ text: "Conclusion", heading: "Heading2" }),
        new Paragraph(c.conclusion)

      ]

    }]

  });

  return await Packer.toBuffer(doc);

};

module.exports = {
  generatePDF,
  generateDOCX
};*/
/*const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, Table, TableRow, TableCell, WidthType } = require("docx");

function parseContent(report) {

  if (typeof report.content === "string") {
    try {
      return JSON.parse(report.content);
    } catch {
      return {};
    }
  }

  return report.content || {};

}


/*
=====================================
PDF GENERATOR
=====================================
*/

/*const generatePDF = async (report) => {

  return new Promise((resolve) => {

    const doc = new PDFDocument({ margin: 50 });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const c = parseContent(report);

    /* TITLE 

    doc.fontSize(20).text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });
    doc.moveDown(2);


    /* EXECUTIVE SUMMARY 

    doc.fontSize(14).fillColor("#000").text("Executive Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      (c.executiveSummary || "") +
      "\n\nThe forensic analysis focused on identifying suspicious artifacts, system changes, and external communications that could indicate unauthorized activity."
    );

    doc.moveDown(2);


    /* INCIDENT OVERVIEW 

    doc.fontSize(14).text("Incident Overview", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      (c.incidentOverview || "") +
      "\n\nThe investigation included examination of file system artifacts, network traffic indicators, and user activity logs."
    );

    doc.moveDown(2);


    /* EVIDENCE SUMMARY TABLE 

    doc.fontSize(14).text("Evidence Summary", { underline: true });
    doc.moveDown();

    const evidenceTable = [
      ["Evidence Type", "Description"],
      ["Suspicious File", "system_update_patch.scr"],
      ["Browser History", "Access to suspicious portal"],
      ["Network Logs", "Connection to external IP"],
      ["Registry Entry", "Persistence mechanism detected"],
      ["Email Artifact", "Email containing suspicious attachment"]
    ];

    evidenceTable.forEach((row, i) => {

      doc.fontSize(11);

      doc.text(
        row[0].padEnd(25) + " | " + row[1],
        {
          width: 500,
          align: "left"
        }
      );

      if (i === 0) {
        doc.moveDown(0.2);
        doc.text("-----------------------------------------------------------");
      }

    });

    doc.moveDown(2);


    /* TECHNICAL FINDINGS 

    doc.fontSize(14).text("Technical Findings", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      (c.technicalFindings || "") +
      "\n\nFurther examination confirmed the presence of suspicious system behavior and persistence indicators suggesting malicious execution."
    );

    doc.moveDown(2);


    /* TIMELINE TABLE 

    doc.fontSize(14).text("Timeline of Events", { underline: true });
    doc.moveDown();

    const timelineRows = (c.timeline || "").split("\n");

    doc.text("Time".padEnd(15) + " | Event");
    doc.text("---------------------------------------------");

    timelineRows.forEach(row => {

      const parts = row.trim().split(" ");
      const time = parts.shift();
      const event = parts.join(" ");

      doc.text(time.padEnd(15) + " | " + event);

    });

    doc.moveDown(2);


    /* CONCLUSION 

    doc.fontSize(14).text("Conclusion", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      (c.conclusion || "") +
      "\n\nIt is recommended that the affected system undergo a complete malware analysis and that monitoring controls be implemented to prevent similar incidents."
    );


    doc.end();

  });

};



/*
=====================================
DOCX GENERATOR
=====================================
*/

/*const generateDOCX = async (report) => {

  const c = parseContent(report);

  const evidenceRows = [
    ["Evidence Type", "Description"],
    ["Suspicious File", "system_update_patch.scr"],
    ["Browser History", "Access to suspicious portal"],
    ["Network Logs", "Connection to external IP"],
    ["Registry Entry", "Persistence mechanism detected"],
    ["Email Artifact", "Email containing suspicious attachment"]
  ];

  const timelineRows = (c.timeline || "").split("\n").map(row => {
    const parts = row.split(" ");
    return [parts.shift(), parts.join(" ")];
  });


  const evidenceTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: evidenceRows.map(r => new TableRow({
      children: r.map(cell => new TableCell({
        children: [new Paragraph(cell)]
      }))
    }))
  });


  const timelineTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph("Time")] }),
          new TableCell({ children: [new Paragraph("Event")] })
        ]
      }),
      ...timelineRows.map(r => new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(r[0])] }),
          new TableCell({ children: [new Paragraph(r[1])] })
        ]
      }))
    ]
  });


  const doc = new Document({

    sections: [{

      children: [

        new Paragraph({ text: "DIGITAL FORENSIC INVESTIGATION REPORT", heading: "Heading1" }),

        new Paragraph(""),

        new Paragraph({ text: "Executive Summary", heading: "Heading2" }),
        new Paragraph(c.executiveSummary),

        new Paragraph(""),

        new Paragraph({ text: "Incident Overview", heading: "Heading2" }),
        new Paragraph(c.incidentOverview),

        new Paragraph(""),

        new Paragraph({ text: "Evidence Summary", heading: "Heading2" }),
        evidenceTable,

        new Paragraph(""),

        new Paragraph({ text: "Technical Findings", heading: "Heading2" }),
        new Paragraph(c.technicalFindings),

        new Paragraph(""),

        new Paragraph({ text: "Timeline of Events", heading: "Heading2" }),
        timelineTable,

        new Paragraph(""),

        new Paragraph({ text: "Conclusion", heading: "Heading2" }),
        new Paragraph(c.conclusion)

      ]

    }]

  });

  return await Packer.toBuffer(doc);

};


module.exports = {
  generatePDF,
  generateDOCX
};*/
/*const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, Table, TableRow, TableCell, WidthType } = require("docx");

/* -------------------------------------------------------
PARSE REPORT CONTENT
------------------------------------------------------- *

function parseContent(report) {

  if (typeof report.content === "string") {
    try {
      return JSON.parse(report.content);
    } catch {
      return {};
    }
  }

  return report.content || {};

}


/* -------------------------------------------------------
PDF GENERATOR
------------------------------------------------------- *

const generatePDF = async (report) => {

  return new Promise((resolve) => {

    const doc = new PDFDocument({ margin: 50 });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const c = parseContent(report);


    /* -------------------------------------------------------
    TITLE
    ------------------------------------------------------- *

    doc.fontSize(20)
      .text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });

    doc.moveDown();

    doc.fontSize(11)
      .text(`Report ID : ${report.reportId}`)
      .text(`Case ID   : ${report.caseId?.caseId || ""}`)
      .text(`Generated : ${new Date(report.createdAt).toLocaleString()}`);

    doc.moveDown(2);


    /* -------------------------------------------------------
    EXECUTIVE SUMMARY
    ------------------------------------------------------- *

    doc.fontSize(14).text("Executive Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      `${c.executiveSummary}

This forensic investigation was conducted to determine the nature of suspicious activities detected on the workstation. During the examination investigators identified several artifacts including abnormal browser activity, suspicious file downloads, and unusual outbound network communication. 

The analysis aimed to determine the possible source of compromise, identify malicious indicators, and reconstruct the sequence of events that occurred on the affected system. Findings from this investigation help security teams understand the impact of the incident and implement preventive controls to mitigate similar threats in the future.`
    );

    doc.moveDown(2);


    /* -------------------------------------------------------
    INCIDENT OVERVIEW
    ------------------------------------------------------- *

    doc.fontSize(14).text("Incident Overview", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      `${c.incidentOverview}

The system examined during the investigation was connected to an internal corporate network used by employees for routine business operations. Security monitoring tools detected abnormal network activity originating from the workstation, prompting a detailed forensic examination.

Investigators analyzed system logs, file system artifacts, registry entries, browser history records, and network communication logs to identify the source and nature of the suspicious activity.`
    );

    doc.moveDown(2);


    /* -------------------------------------------------------
    EVIDENCE SUMMARY TABLE
    ------------------------------------------------------- *

    doc.fontSize(14).text("Evidence Summary", { underline: true });
    doc.moveDown();

    const evidenceTable = [
      ["Evidence Type", "Description"],
      ["Suspicious File", "system_update_patch.scr"],
      ["Browser History", "Access to suspicious portal and unknown file sharing sites"],
      ["Network Logs", "Outbound connection to external IP over port 8080"],
      ["Registry Entry", "Persistence mechanism referencing suspicious executable"],
      ["Email Artifact", "Phishing email containing malicious attachment"]
    ];

    let startY = doc.y;
    let rowHeight = 25;

    evidenceTable.forEach((row, i) => {

      let y = startY + (i * rowHeight);

      doc.rect(50, y, 200, rowHeight).stroke();
      doc.rect(250, y, 300, rowHeight).stroke();

      doc.fontSize(11).text(row[0], 55, y + 8, { width: 190 });
      doc.text(row[1], 255, y + 8, { width: 290 });

    });

    doc.moveDown(6);


    /* -------------------------------------------------------
    TECHNICAL FINDINGS
    ------------------------------------------------------- *

    doc.fontSize(14).text("Technical Findings", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      `${c.technicalFindings}

Detailed analysis revealed that a suspicious executable file was downloaded and executed by the user. Browser artifacts showed that the user accessed unknown websites that host downloadable content. Network logs confirmed that the workstation initiated communication with an external server shortly after the file download occurred.

Registry examination revealed persistence mechanisms that may allow the suspicious file to execute automatically when the user logs into the system. These indicators strongly suggest the possibility of malware delivery through phishing or malicious downloads.`
    );

    doc.moveDown(2);


    /* -------------------------------------------------------
    TIMELINE TABLE
    ------------------------------------------------------- *

    doc.fontSize(14).text("Timeline of Events", { underline: true });
    doc.moveDown();

    const timelineRows = (c.timeline || "").split("\n");

    const timelineData = [["Time", "Event"]];

    timelineRows.forEach(row => {
      const parts = row.split(" ");
      timelineData.push([parts.shift(), parts.join(" ")]);
    });

    let timelineStart = doc.y;

    timelineData.forEach((row, i) => {

      let y = timelineStart + (i * rowHeight);

      doc.rect(50, y, 150, rowHeight).stroke();
      doc.rect(200, y, 350, rowHeight).stroke();

      doc.fontSize(11).text(row[0], 55, y + 8);
      doc.text(row[1], 205, y + 8);

    });

    doc.moveDown(6);


    /* -------------------------------------------------------
    CONCLUSION
    ------------------------------------------------------- *

    doc.fontSize(14).text("Conclusion", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(11).text(
      `${c.conclusion}

The forensic investigation identified multiple indicators consistent with malicious activity including suspicious file execution, abnormal network communication, and registry persistence artifacts. These findings indicate that the system may have been compromised through phishing-based malware delivery.

It is recommended that the affected system undergo a full malware analysis, network monitoring be enhanced, and security awareness training be provided to users to prevent similar incidents.`
    );

    doc.end();

  });

};



/* -------------------------------------------------------
DOCX GENERATOR
------------------------------------------------------- *

const generateDOCX = async (report) => {

  const c = parseContent(report);

  const evidenceRows = [
    ["Evidence Type", "Description"],
    ["Suspicious File", "system_update_patch.scr"],
    ["Browser History", "Access to suspicious portal and unknown download sites"],
    ["Network Logs", "Outbound connection to external IP"],
    ["Registry Entry", "Persistence mechanism detected"],
    ["Email Artifact", "Phishing email with malicious attachment"]
  ];

  const timelineRows = (c.timeline || "").split("\n").map(row => {
    const parts = row.split(" ");
    return [parts.shift(), parts.join(" ")];
  });


  const evidenceTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: evidenceRows.map(r => new TableRow({
      children: r.map(cell => new TableCell({
        children: [new Paragraph(cell)]
      }))
    }))
  });

  const timelineTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph("Time")] }),
          new TableCell({ children: [new Paragraph("Event")] })
        ]
      }),
      ...timelineRows.map(r => new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(r[0])] }),
          new TableCell({ children: [new Paragraph(r[1])] })
        ]
      }))
    ]
  });


  const doc = new Document({

    sections: [{

      children: [

        new Paragraph({ text: "DIGITAL FORENSIC INVESTIGATION REPORT", heading: "Heading1" }),

        new Paragraph(""),

        new Paragraph({ text: "Executive Summary", heading: "Heading2" }),
        new Paragraph(c.executiveSummary),

        new Paragraph(""),

        new Paragraph({ text: "Incident Overview", heading: "Heading2" }),
        new Paragraph(c.incidentOverview),

        new Paragraph(""),

        new Paragraph({ text: "Evidence Summary", heading: "Heading2" }),
        evidenceTable,

        new Paragraph(""),

        new Paragraph({ text: "Technical Findings", heading: "Heading2" }),
        new Paragraph(c.technicalFindings),

        new Paragraph(""),

        new Paragraph({ text: "Timeline of Events", heading: "Heading2" }),
        timelineTable,

        new Paragraph(""),

        new Paragraph({ text: "Conclusion", heading: "Heading2" }),
        new Paragraph(c.conclusion)

      ]

    }]

  });

  return await Packer.toBuffer(doc);

};

module.exports = {
  generatePDF,
  generateDOCX
};*/
/*const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, Table, TableRow, TableCell, WidthType } = require("docx");

function parseContent(report) {

  if (typeof report.content === "string") {
    try {
      return JSON.parse(report.content);
    } catch {
      return {};
    }
  }

  return report.content || {};
}


/* --------------------------------------------------
PDF GENERATION
-------------------------------------------------- 

const generatePDF = async (report) => {

  return new Promise(resolve => {

    const doc = new PDFDocument({ margin: 50 });

    const buffers = [];
    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const c = parseContent(report);


    /* TITLE 

    doc.fontSize(20).text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });
    doc.moveDown();

    doc.fontSize(11)
      .text(`Report ID : ${report.reportId}`)
      .text(`Case ID : ${report.caseId?.caseId}`)
      .text(`Generated : ${new Date(report.createdAt).toLocaleString()}`);

    doc.moveDown(2);


    /* EXECUTIVE SUMMARY 

    doc.fontSize(14).text("Executive Summary", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(c.executiveSummary);
    doc.moveDown(2);


    /* INCIDENT OVERVIEW 

    doc.fontSize(14).text("Incident Overview", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(c.incidentOverview);
    doc.moveDown(2);


    /* EVIDENCE TABLE 

    doc.fontSize(14).text("Evidence Summary", { underline: true });
    doc.moveDown();

    const evidenceRows = [
      ["Evidence Type", "Description"],
      ["Suspicious File", "system_update_patch.scr"],
      ["Browser History", "Access to suspicious portal"],
      ["Network Logs", "Connection to external IP"],
      ["Registry Entry", "Persistence mechanism detected"],
      ["Email Artifact", "Phishing email attachment"]
    ];

    let startY = doc.y;
    let rowHeight = 25;

    evidenceRows.forEach((row, i) => {

      let y = startY + i * rowHeight;

      doc.rect(50, y, 200, rowHeight).stroke();
      doc.rect(250, y, 300, rowHeight).stroke();

      doc.fontSize(11).text(row[0], 55, y + 8);
      doc.text(row[1], 255, y + 8);

    });

    doc.moveDown(6);


    /* TECHNICAL FINDINGS 

    doc.fontSize(14).text("Technical Findings", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(c.technicalFindings);
    doc.moveDown(2);


    /* TIMELINE 

    doc.fontSize(14).text("Timeline of Events", { underline: true });
    doc.moveDown();

    const timeline = (c.timeline || "").split("\n");

    let timelineData = [["Time", "Event"]];

    timeline.forEach(r => {
      const p = r.split(" ");
      timelineData.push([p.shift(), p.join(" ")]);
    });

    let tStart = doc.y;

    timelineData.forEach((row, i) => {

      let y = tStart + i * rowHeight;

      doc.rect(50, y, 150, rowHeight).stroke();
      doc.rect(200, y, 350, rowHeight).stroke();

      doc.text(row[0], 55, y + 8);
      doc.text(row[1], 205, y + 8);

    });

    doc.moveDown(6);


    /* CONCLUSION 

    doc.fontSize(14).text("Conclusion", { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(c.conclusion);

    doc.end();

  });

};


/* --------------------------------------------------
DOCX GENERATION
-------------------------------------------------- 

const generateDOCX = async (report) => {

  const c = parseContent(report);

  const evidenceTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      ["Evidence Type", "Description"],
      ["Suspicious File", "system_update_patch.scr"],
      ["Browser History", "Access to suspicious portal"],
      ["Network Logs", "External IP connection"],
      ["Registry Entry", "Persistence mechanism detected"],
      ["Email Artifact", "Phishing email attachment"]
    ].map(r => new TableRow({
      children: r.map(cell => new TableCell({
        children: [new Paragraph(cell)]
      }))
    }))
  });

  const timelineRows = (c.timeline || "").split("\n").map(row => {
    const p = row.split(" ");
    return [p.shift(), p.join(" ")];
  });

  const timelineTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph("Time")] }),
          new TableCell({ children: [new Paragraph("Event")] })
        ]
      }),
      ...timelineRows.map(r => new TableRow({
        children: [
          new TableCell({ children: [new Paragraph(r[0])] }),
          new TableCell({ children: [new Paragraph(r[1])] })
        ]
      }))
    ]
  });

  const doc = new Document({
    sections: [{
      children: [

        new Paragraph({ text: "DIGITAL FORENSIC INVESTIGATION REPORT", heading: "Heading1" }),

        new Paragraph(""),

        new Paragraph({ text: "Executive Summary", heading: "Heading2" }),
        new Paragraph(c.executiveSummary),

        new Paragraph(""),

        new Paragraph({ text: "Incident Overview", heading: "Heading2" }),
        new Paragraph(c.incidentOverview),

        new Paragraph(""),

        new Paragraph({ text: "Evidence Summary", heading: "Heading2" }),
        evidenceTable,

        new Paragraph(""),

        new Paragraph({ text: "Technical Findings", heading: "Heading2" }),
        new Paragraph(c.technicalFindings),

        new Paragraph(""),

        new Paragraph({ text: "Timeline of Events", heading: "Heading2" }),
        timelineTable,

        new Paragraph(""),

        new Paragraph({ text: "Conclusion", heading: "Heading2" }),
        new Paragraph(c.conclusion)

      ]
    }]
  });

  return await Packer.toBuffer(doc);

};

module.exports = {
  generatePDF,
  generateDOCX
};*/
/*const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph, Table, TableRow, TableCell, WidthType } = require("docx");

/*
-----------------------------------------
GENERATE PDF
-----------------------------------------


const generatePDF = async (report) => {

  return new Promise((resolve) => {

    const doc = new PDFDocument({
      margin: 50,
      size: "A4"
    });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));

    doc.on("end", () => {
      resolve(Buffer.concat(buffers));
    });

    const content = typeof report.content === "string"
      ? JSON.parse(report.content)
      : report.content;

    /*
    TITLE
    *

    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });

    doc.moveDown();

    doc.fontSize(12).font("Helvetica");

    doc.text(`Report ID : ${report.reportId}`);
    doc.text(`Case ID : ${report.caseId?.caseId || "N/A"}`);
    doc.text(`Generated : ${new Date().toLocaleString()}`);

    doc.moveDown(2);

    /*
    EXECUTIVE SUMMARY
    *

    doc.font("Helvetica-Bold").fontSize(16).text("Executive Summary");
    doc.moveDown(0.5);

    doc.font("Helvetica").fontSize(12).text(content.executiveSummary, {
      align: "justify"
    });

    doc.moveDown(2);

    /*
    INCIDENT OVERVIEW
    *

    doc.font("Helvetica-Bold").fontSize(16).text("Incident Overview");
    doc.moveDown(0.5);

    doc.font("Helvetica").fontSize(12).text(content.incidentOverview, {
      align: "justify"
    });

    doc.moveDown(2);

    /*
    EVIDENCE SUMMARY TABLE
    *

    doc.font("Helvetica-Bold").fontSize(16).text("Evidence Summary");

    doc.moveDown();

    const evidenceTable = [
      ["Evidence Type", "Description"],
      ["Suspicious File", "system_update_patch.scr"],
      ["Browser History", "Access to suspicious portal"],
      ["Network Logs", "Connection to external IP"],
      ["Registry Entry", "Persistence mechanism detected"],
      ["Email Artifact", "Phishing email attachment"]
    ];

    const tableTop = doc.y;

    const col1 = 200;
    const col2 = 330;
    const rowHeight = 25;

    evidenceTable.forEach((row, i) => {

      const y = tableTop + i * rowHeight;

      doc.rect(50, y, col1, rowHeight).stroke();
      doc.rect(250, y, col2, rowHeight).stroke();

      doc.font("Helvetica-Bold").fontSize(11)
        .text(row[0], 55, y + 8, { width: col1 - 10 });

      doc.font("Helvetica").fontSize(11)
        .text(row[1], 255, y + 8, { width: col2 - 10 });

    });

    doc.moveDown(6);

    /*
    TECHNICAL FINDINGS
    *

    doc.font("Helvetica-Bold").fontSize(16).text("Technical Findings");
    doc.moveDown(0.5);

    doc.font("Helvetica").fontSize(12).text(content.technicalFindings, {
      align: "justify"
    });

    doc.moveDown(2);

    /*
    TIMELINE TABLE
    *

    doc.font("Helvetica-Bold").fontSize(16).text("Timeline of Events");

    doc.moveDown();

    const timelineEvents = content.timeline.split("\n");

    const timelineTable = [
      ["Time", "Event"],
      ...timelineEvents.map(e => {
        const parts = e.split(" ");
        return [parts.shift(), parts.join(" ")];
      })
    ];

    const timelineTop = doc.y;

    timelineTable.forEach((row, i) => {

      const y = timelineTop + i * rowHeight;

      doc.rect(50, y, col1, rowHeight).stroke();
      doc.rect(250, y, col2, rowHeight).stroke();

      doc.font("Helvetica-Bold").fontSize(11)
        .text(row[0], 55, y + 8, { width: col1 - 10 });

      doc.font("Helvetica").fontSize(11)
        .text(row[1], 255, y + 8, { width: col2 - 10 });

    });

    doc.moveDown(6);

    /*
    CONCLUSION
    *

    doc.font("Helvetica-Bold").fontSize(16).text("Conclusion");
    doc.moveDown(0.5);

    doc.font("Helvetica").fontSize(12).text(content.conclusion, {
      align: "justify"
    });

    doc.end();
  });
};


/*
-----------------------------------------
GENERATE DOCX
-----------------------------------------
*

const generateDOCX = async (report) => {

  const content = typeof report.content === "string"
    ? JSON.parse(report.content)
    : report.content;

  const doc = new Document({
    sections: [
      {
        children: [

          new Paragraph({
            text: "DIGITAL FORENSIC INVESTIGATION REPORT",
            heading: "Heading1"
          }),

          new Paragraph(`Report ID : ${report.reportId}`),
          new Paragraph(`Case ID : ${report.caseId?.caseId || "N/A"}`),

          new Paragraph(""),

          new Paragraph({
            text: "Executive Summary",
            heading: "Heading2"
          }),

          new Paragraph(content.executiveSummary),

          new Paragraph(""),

          new Paragraph({
            text: "Incident Overview",
            heading: "Heading2"
          }),

          new Paragraph(content.incidentOverview),

          new Paragraph(""),

          new Paragraph({
            text: "Technical Findings",
            heading: "Heading2"
          }),

          new Paragraph(content.technicalFindings),

          new Paragraph(""),

          new Paragraph({
            text: "Timeline of Events",
            heading: "Heading2"
          }),

          new Paragraph(content.timeline),

          new Paragraph(""),

          new Paragraph({
            text: "Conclusion",
            heading: "Heading2"
          }),

          new Paragraph(content.conclusion)

        ]
      }
    ]
  });

  return await Packer.toBuffer(doc);
};

module.exports = {
  generatePDF,
  generateDOCX
};*/
const PDFDocument = require("pdfkit");
const { Document, Packer, Paragraph } = require("docx");

/*
-------------------------------------
GENERATE PDF
-------------------------------------
*/

const generatePDF = async (report) => {

  return new Promise((resolve) => {

    const doc = new PDFDocument({ margin: 50 });

    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const content =
      typeof report.content === "string"
        ? JSON.parse(report.content)
        : report.content;


    /*
    TITLE
    */

    doc.fontSize(20).font("Helvetica-Bold")
      .text("DIGITAL FORENSIC INVESTIGATION REPORT", { align: "center" });

    doc.moveDown();

    doc.fontSize(12).font("Helvetica");

    doc.text(`Report ID : ${report.reportId}`);
    doc.text(`Case : ${report.caseId?.caseId || "N/A"}`);

    doc.moveDown(2);


    /*
    EXECUTIVE SUMMARY
    */

    doc.fontSize(16).font("Helvetica-Bold")
      .text("Executive Summary");

    doc.moveDown();

    doc.fontSize(12).font("Helvetica")
      .text(content.executiveSummary);

    doc.moveDown(2);


    /*
    INCIDENT OVERVIEW
    */

    doc.fontSize(16).font("Helvetica-Bold")
      .text("Incident Overview");

    doc.moveDown();

    doc.fontSize(12).font("Helvetica")
      .text(content.incidentOverview);

    doc.moveDown(2);


    /*
    EVIDENCE TABLE
    */

    doc.fontSize(16).font("Helvetica-Bold")
      .text("Evidence Summary");

    doc.moveDown();

    const evidenceRows = [
      ["Evidence Type", "Description"],
      ["Suspicious File", "system_update_patch.scr"],
      ["Browser History", "Access to suspicious portal"],
      ["Network Logs", "Connection to external IP"],
      ["Registry Entry", "Persistence mechanism detected"],
      ["Email Artifact", "Email containing suspicious attachment"]
    ];

    let y = doc.y;

    /* Prevent table breaking across pages */
    if (y + 200 > doc.page.height) {
      doc.addPage();
      y = doc.y;
    }

    const tableX = 50;
    const col1 = 200;
    const col2 = 330;
    const rowHeight = 25;

    evidenceRows.forEach((row, i) => {

      doc.rect(tableX, y, col1, rowHeight).stroke();
      doc.rect(tableX + col1, y, col2, rowHeight).stroke();

      doc.font(i === 0 ? "Helvetica-Bold" : "Helvetica")
        .fontSize(11)
        .text(row[0], tableX + 5, y + 7, { width: col1 - 10 });

      doc.font(i === 0 ? "Helvetica-Bold" : "Helvetica")
        .fontSize(11)
        .text(row[1], tableX + col1 + 5, y + 7, { width: col2 - 10 });

      y += rowHeight;

    });

    doc.y = y + 30;
    doc.x = doc.page.margins.left;


    /*
    TECHNICAL FINDINGS
    */

    doc.fontSize(16).font("Helvetica-Bold")
      .text("Technical Findings");

    doc.moveDown();

    doc.fontSize(12).font("Helvetica")
      .text(content.technicalFindings);

    doc.moveDown(2);


    /*
    TIMELINE TABLE
    */

    doc.fontSize(16).font("Helvetica-Bold")
      .text("Timeline of Events");

    doc.moveDown();

    const timelineRows = [
      ["Time", "Event"],
      ...content.timeline
        .replace(/,/g, "\n")
        .split("\n")
        .filter(Boolean)
        .map(e => {
          const parts = e.trim().split(" ");
          const time = parts.shift();
          return [time, parts.join(" ")];
        })
    ];

    y = doc.y;

    /* Prevent timeline table breaking */
    if (y + 200 > doc.page.height) {
      doc.addPage();
      y = doc.y;
    }

    const timeCol = 120;
    const eventCol = 410;

    timelineRows.forEach((row, i) => {

      doc.rect(tableX, y, timeCol, rowHeight).stroke();
      doc.rect(tableX + timeCol, y, eventCol, rowHeight).stroke();

      doc.font(i === 0 ? "Helvetica-Bold" : "Helvetica")
        .fontSize(11)
        .text(row[0], tableX + 5, y + 7, { width: timeCol - 10 });

      doc.font(i === 0 ? "Helvetica-Bold" : "Helvetica")
        .fontSize(11)
        .text(row[1], tableX + timeCol + 5, y + 7, { width: eventCol - 10 });

      y += rowHeight;

    });

    doc.y = y + 30;
    doc.x = doc.page.margins.left;


    /*
    CONCLUSION
    */

    doc.fontSize(16).font("Helvetica-Bold")
      .text("Conclusion");

    doc.moveDown();

    doc.fontSize(12).font("Helvetica")
      .text(content.conclusion);


    doc.end();

  });

};


/*
-------------------------------------
GENERATE DOCX
-------------------------------------
*/

const generateDOCX = async (report) => {

  const content =
    typeof report.content === "string"
      ? JSON.parse(report.content)
      : report.content;

  const doc = new Document({
    sections: [
      {
        children: [

          new Paragraph({
            text: "DIGITAL FORENSIC INVESTIGATION REPORT",
            heading: "Heading1"
          }),

          new Paragraph(`Report ID : ${report.reportId}`),
          new Paragraph(`Case : ${report.caseId?.caseId || "N/A"}`),

          new Paragraph(""),

          new Paragraph({ text: "Executive Summary", heading: "Heading2" }),
          new Paragraph(content.executiveSummary),

          new Paragraph(""),

          new Paragraph({ text: "Incident Overview", heading: "Heading2" }),
          new Paragraph(content.incidentOverview),

          new Paragraph(""),

          new Paragraph({ text: "Technical Findings", heading: "Heading2" }),
          new Paragraph(content.technicalFindings),

          new Paragraph(""),

          new Paragraph({ text: "Timeline of Events", heading: "Heading2" }),
          new Paragraph(content.timeline),

          new Paragraph(""),

          new Paragraph({ text: "Conclusion", heading: "Heading2" }),
          new Paragraph(content.conclusion)

        ]
      }
    ]
  });

  return await Packer.toBuffer(doc);

};

module.exports = {
  generatePDF,
  generateDOCX
};